servidor/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vapunto/', include('vapunto.urls')),
]

vapunto/urls.py
from mimetypes import init
from django.urls import path

from vapunto import views

urlpatterns = [
    path('', views.login, name='login'),
    path('index', views.index, name='index'),
    path('port', views.port, name='port'),
    path('error_403', views.error_403, name='error_403'),
    path('product', views.product, name='product'),
    path('modproducto/<int:prod_actual>', views.modproducto, name="modproducto"),
    path('borrproducto/<int:prod_actual>', views.borrproducto, name="borrproducto"),
    path('compras', views.compras, name='compras'),
    path('modcompra/<int:prod_actual>', views.modcompra, name="modcompra"),
    path('salir', views.salir, name='salir'),
    path('verusuario', views.verusuario, name='verusuario'),
    path('modusuario/<int:usu_actual>',  views.modusuario, name='modusuario'),
    path('borusuario/<int:usu_actual>', views.borusuario, name='borusuario'),
    path('vercliente', views.vercliente, name='vercliente'),
    path('modcliente/<int:cli_actual>', views.modcliente, name="modcliente"),
    path('borcliente/<int:cli_actual>', views.borcliente, name="borcliente"),
    path('proveedor', views.proveedor, name='proveedor'),
    path('modprovee/<int:pro_actual>', views.modprovee, name="modprovee"),
    path('borprovee/<int:pro_actual>', views.borprovee, name="borprovee"),
    path('pais', views.pais, name='pais'),
    path('modpais/<int:pai_actual>', views.modpais, name="modpais"),
    path('borpais/<int:pai_actual>', views.borpais, name="borpais"),
    path('ciudad', views.ciudad, name='ciudad'),
    path('modciudad/<int:ciu_actual>', views.modciudad, name="modciudad"),
    path('borciudad/<int:ciu_actual>', views.borciudad, name="borciudad"),
    path('fondos/<int:caja_actual>', views.fondos, name='fondos'),
    path('Auditoria', views.audirep, name='Auditoria'),
    path('venta', views.venta, name='venta'),
    path('venta_detalle', views.venta_detalle, name='venta_detalle'),
    path('r_venta', views.registro, name='r_venta'),
    path(r'registro/<int:sale_id>', views.detailprod, name='detailprod')
]

vapunto/models.py
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields.related import ForeignKey

from datetime import datetime


# Create your models here.

   
class Usuariosid(models.Model):
    codigo_usuario = models.AutoField(primary_key = True)
    nombre_usuario = models.CharField(max_length = 50)
    password_usuario = models.CharField(max_length = 50)
    nombre_completo_usuario = models.CharField(max_length = 200)
    tipo_usuario=models.IntegerField()

class Nacionalidad(models.Model):
    codigo_nacionalidad = models.AutoField(primary_key = True)
    nacionalidad = models.CharField(max_length = 50)

class Ciudad(models.Model):
    codigo_ciudad = models.AutoField(primary_key = True)
    ciudad = models.CharField(max_length = 50)

class Proveedor(models.Model):
    codigo_proveedor=models.AutoField(primary_key=True)
    nombre_proveedor= models.CharField(max_length = 50)
    ruc_proveedor= models.IntegerField()
    telefono_proveedor= models.IntegerField()
    nacionalidad = models.ForeignKey(Nacionalidad ,on_delete=models.CASCADE,null=True)
    ciudad = models.ForeignKey(Ciudad ,on_delete=models.CASCADE,null=True)

class producto(models.Model):
    codigo_productos=models.IntegerField(primary_key=True)
    nombre_productos= models.CharField(max_length = 50)
    preciocompra_productos= models.DecimalField(max_digits=9, decimal_places=2)
    precioventa_productos= models.DecimalField( max_digits=9, decimal_places=2)
    categoria_productos= models.CharField(max_length = 50)
    cantidad_productos=models.IntegerField()
    fecha_productos=models.DateField()
    nombre_proveedor = models.ForeignKey(Proveedor ,on_delete=models.CASCADE,null=True)


class Clientes(models.Model):
    codigo_cliente = models.AutoField(primary_key = True)
    ruc_cliente = models.CharField(max_length = 50)
    nombre_cliente = models.CharField(max_length = 50)
    apellido_cliente = models.CharField(max_length = 50)
    telefono_cliente = models.CharField(max_length = 200)
    nacionalidad = models.ForeignKey(Nacionalidad ,on_delete=models.CASCADE,null=True)
    ciudad = models.ForeignKey(Ciudad ,on_delete=models.CASCADE,null=True)

class Clientes2(models.Model):
    codigo_cliente = models.IntegerField(primary_key=True)
    ruc_cliente = models.CharField(max_length = 50)
    nombre_cliente = models.CharField(max_length = 50)
    apellido_cliente = models.CharField(max_length = 50)
    telefono_cliente = models.CharField(max_length = 200)
    nacionalidad = models.ForeignKey(Nacionalidad ,on_delete=models.CASCADE,null=True)
    ciudad = models.ForeignKey(Ciudad ,on_delete=models.CASCADE,null=True)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)

class producto2(models.Model):
    codigo_productos=models.IntegerField(primary_key=True)
    nombre_productos= models.CharField(max_length = 50)
    preciocompra_productos= models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    precioventa_productos= models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    categoria_productos= models.CharField(max_length = 50)
    cantidad_productos=models.IntegerField()
    fecha_productos=models.DateField()
    nombre_proveedor = models.ForeignKey(Proveedor ,on_delete=models.CASCADE,null=True)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)

class Proveedor2(models.Model):
    codigo_proveedor=models.IntegerField(primary_key=True)
    nombre_proveedor= models.CharField(max_length = 50)
    ruc_proveedor= models.IntegerField()
    telefono_proveedor= models.IntegerField()
    nacionalidad = models.ForeignKey(Nacionalidad ,on_delete=models.CASCADE,null=True)
    ciudad = models.ForeignKey(Ciudad ,on_delete=models.CASCADE,null=True)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)

class Nacionalidad2(models.Model):
    codigo_nacionalidad = models.IntegerField(primary_key=True)
    nacionalidad = models.CharField(max_length = 50)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)

class Ciudad2(models.Model):
    codigo_ciudad = models.IntegerField(primary_key=True)
    ciudad = models.CharField(max_length = 50)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)

class Caja(models.Model):
    codigo_caja = models.AutoField(primary_key=True)
    fecha_caja = models.CharField(max_length = 50)
    hora_caja = models.TimeField()
    motivo_caja = models.CharField(max_length = 50, null=True)
    entrada_caja=models.DecimalField(default=0.00, max_digits=12, decimal_places=2,null=True)
    salida_caja=models.DecimalField(default=0.00, max_digits=12, decimal_places=2,null=True)
    estado_caja = models.IntegerField(null=True)
    codigo_usuario = models.IntegerField()
    nombre_usuario = models.CharField(max_length = 50)
    total_caja=models.IntegerField()

class cajaDinero(models.Model):
    codigo_caja_dinero=models.AutoField(primary_key=True)
    total_caja = models.DecimalField(default=0.00, max_digits=9, decimal_places=2, null=True)

class MethodPay(models.Model):
    name = models.CharField(max_length=150)


class Sale(models.Model):
    sale_id = models.AutoField(primary_key=True)
    cli = models.ForeignKey(Clientes ,on_delete=models.CASCADE,null=True)
    date_joined = models.DateField(default=datetime.now)
    pay = models.ForeignKey(MethodPay ,on_delete=models.CASCADE,null=True)
    iva = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    subtotalsuma = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

class DetSale(models.Model):
    detsale_id = models.AutoField(primary_key=True)
    sale = models.ForeignKey(Sale, on_delete=models.CASCADE)
    prod = models.ForeignKey(producto, on_delete=models.CASCADE)
    cant = models.IntegerField()
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
  

vapunto/templates/Auditoria.html
{%extends "index.html"%}

{%block formulario%}

{%load static%}

<div class="col-lg-12">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Lista De Clientes Alterados
      </h5>
      <div class="table-responsive">
        <table class="table" id="datos2">
          <thead>
            <tr>
              <th>Id</th>
              <th>RUC</th>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Telefono</th>
              <th>Nacionalidad</th>
              <th>Ciudad</th>
              <th>Nombre del Usuario</th>
            </tr>
          </thead>
          <tbody>
            {% for lista in parameters.listacliente %}

            <tr>
              <td>{{ lista.codigo_cliente }}</td>
              <td>{{ lista.ruc_cliente }}</td>
              <td>{{ lista.nombre_cliente }}</td>
              <td>{{ lista.apellido_cliente }}</td>
              <td>{{ lista.telefono_cliente }}</td>
              
              {% for nacio in parameters.listapai %}
              {% if nacio.codigo_nacionalidad == lista.nacionalidad_id %}
              <td>{{ nacio.nacionalidad }}</td>
              {%endif%}
              {%endfor%}

              {% for ciu in parameters.listaciu %}
              {% if ciu.codigo_ciudad == lista.ciudad_id %}
              <td>{{ ciu.ciudad }}</td>
              {%endif%}
              {%endfor%}
              <td>{{ lista.nombre_usuario }}</td>
            </tr>
            {% endfor %}
            

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Lista De Proveedores Alterados
        </h5>
        <div class="table-responsive">
          <table class="table" id="datos">
            <thead>
              <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Ruc</th>
                <th>Telefono</th>
                <th>Nacionalidad</th>
                <th>Ciudad</th>
                <th>Nombre del Usuario</th>
              </tr>
            </thead>
            <tbody>
              {% for lista in parameters.listaprove2 %}
  
              <tr>
                <td>{{ lista.codigo_proveedor }}</td>
                <td>{{ lista.nombre_proveedor }}</td>
                <td>{{ lista.ruc_proveedor }}</td>
                <td>{{ lista.telefono_proveedor }}</td>
  
                {% for nacio in parameters.listapai %}
                {% if nacio.codigo_nacionalidad == lista.nacionalidad_id %}
                <td>{{ nacio.nacionalidad }}</td>
                {%endif%}
                {%endfor%}
  
                {% for ciu in parameters.listaciu %}
                {% if ciu.codigo_ciudad == lista.ciudad_id %}
                <td>{{ ciu.ciudad }}</td>
                {%endif%}
                {%endfor%}
                <td>{{ lista.nombre_usuario }}</td>
                
              </tr>
              {% endfor %}
  
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  
  <div class="col-lg-12">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Lista De Productos Alterados
        </h5>
        <div class="table-responsive">
          <table class="table" id="datos3">
            <thead>
              <tr>
                <th>Codigo</th>
                <th>Nombre</th>
                <th>Precio/compra</th>
                <th>Precio/venta</th>
                <th>Categoria</th>
                <th>Cantidad</th>
                <th>Proveedor</th>
                <th>Fecha</th>
                <th>Nombre del Usuario</th>
              </tr>
            </thead>
            <tbody>
              {% for lista in parameters.listatabla %}
              <tr>
                <td>{{ lista.codigo_productos }}</td>
                <td>{{ lista.nombre_productos }}</td>
                <td>{{ lista.preciocompra_productos }}</td>
                <td>{{ lista.precioventa_productos }}</td>
                <td>{{ lista.categoria_productos }}</td>
                <td>{{ lista.cantidad_productos }}</td>
                {% for prov in parameters.listaprove %}
                {% if prov.codigo_proveedor == lista.nombre_proveedor_id %}
                <td>{{ prov.nombre_proveedor }}</td>
                {%endif%}
                {%endfor%}
                <td>{{ lista.fecha_productos }}</td>
                <td>{{ lista.nombre_usuario }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


<script src="{% static 'assets/js/sweetalert2.all.min.js' %}"></script>

</body>
{%endblock%}

{%block extra%}


  <script>
    $(document).ready(function () {
      $('#datos3').DataTable({
        "language": {
          "emptyTable": "No existen registros a exponer.",
          "info": "",
          "infoEmpty": "",
          "infoFiltered": "",
          "infoPostFix": "",
          "thousands": ".",
          "lengthMenu": "Registros a mostrar _MENU_",
          "loadingRecords": "Cargando...",
          "processing": "Procesando...",
          "search": "Buscar:",
          "zeroRecords": "No se obtuvo ninguna coincidencia",
          oPaginate: {
            sNext: '<i class="fas fa-arrow-circle-right"></i>',
            sPrevious: '<i class="fas fa-arrow-alt-circle-left"></i>',
            sFirst: '<i class="fa fa-step-backward"></i>',
            sLast: '<i class="fa fa-step-forward"></i>'
          }
        }
      });
    });
  </script>
<script>
  $(document).ready(function () {
    $('#datos2').DataTable({
      "language": {
        "emptyTable": "No existen registros a exponer.",
        "info": false,
        "infoEmpty": "",
        "infoFiltered": "",
        "infoPostFix": "",
        "thousands": ".",
        "lengthMenu": "Registros a mostrar _MENU_",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": false,
        "zeroRecords": "No se obtuvo ninguna coincidencia",
        oPaginate: 
          false
      }
    });
  });
</script>

{%endblock%}

vapunto/templates/base.html
{%load static%}
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Punto Vape</title>

    
    <!-- loader-->
    <link href="{%static 'assets/css/pace.min.css'%}" rel="stylesheet"/>
    <script src="{%static 'assets/js/pace.min.js'%}"></script>
    <!--favicon-->
    <link rel="icon" href="{%static 'assets/images/logo.png'%}" type="image/x-icon" height="5" width="5">
    <!-- simplebar CSS-->
    <link href="{%static 'assets/plugins/simplebar/css/simplebar.css'%}" rel="stylesheet"/>
    <!-- Bootstrap core CSS-->
    <link href="{%static 'assets/css/bootstrap.min.css'%}" rel="stylesheet"/>
    <!-- animate CSS-->
    <link href="{%static 'assets/css/animate.css'%}" rel="stylesheet" type="text/css"/>
    <!-- Icons CSS-->
    <link href="{%static 'assets/css/icons.css'%}" rel="stylesheet" type="text/css"/>
    <!-- Sidebar CSS-->
    <link href="{%static 'assets/css/sidebar-menu.css'%}" rel="stylesheet"/>
    <!-- Custom Style-->
    <link href="{%static 'assets/css/app-style.css'%}" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'assets/css/validacion.css'%}">
    
    
    <link href="{%static 'assets/css/fontawesome/css/all.min.css'%}" rel="stylesheet"/>
  </head>
  {%block cuerpo%}
  {%endblock%}
  

  <script src="{%static 'assets/js/jquery.min.js'%}"></script>
  <script src="{%static 'assets/js/popper.min.js'%}"></script>
  <script src="{%static 'assets/js/bootstrap.min.js'%}"></script>
  <script src="{%static 'assets/js/tienda.js'%}"></script>
	
  <!-- sidebar-menu js -->
  <script src="{%static 'assets/js/sidebar-menu.js'%}"></script>
  
  <!-- Custom scripts -->
  <script src="{%static 'assets/js/app-script.js'%}"></script>

  <script src="{% static 'assets/js/sweetalert2.all.min.js' %}"></script>
  <!--dataTable-->
  <script src="{% static 'assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
     
  
  
      
 
  <!--start overlay-->
<div class="overlay toggle-menu"></div>
<!--end overlay-->

</div>
<!-- End container-fluid-->

</div>
<!--End content-wrapper-->
<!--Start Back To Top Button-->
<a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
<!--End Back To Top Button-->

<!--Start footer-->

<!--End footer-->

<!--start color switcher-->
<div class="right-sidebar">
  <div class="switcher-icon">
    <i class="zmdi zmdi-settings zmdi-hc-spin"></i>
  </div>
  <div class="right-sidebar-content">

    <p class="mb-0">Gaussion Texture</p>
    <hr>

    <ul class="switcher">
      <li id="theme1"></li>
      <li id="theme2"></li>
      <li id="theme3"></li>
      <li id="theme4"></li>
      <li id="theme5"></li>
      <li id="theme6"></li>
    </ul>

    <p class="mb-0">Gradient Background</p>
    <hr>

    <ul class="switcher">
      <li id="theme7"></li>
      <li id="theme8"></li>
      <li id="theme9"></li>
      <li id="theme10"></li>
      <li id="theme11"></li>
      <li id="theme12"></li>
      <li id="theme13"></li>
      <li id="theme14"></li>
      <li id="theme15"></li>
    </ul>

  </div>
</div>
  
  <script>
    $(document).ready(function () {
      $('#datos').DataTable({
        "language": {
          "emptyTable": "No existen registros a exponer.",
          "info": "",
          "infoEmpty": "",
          "infoFiltered": "",
          "infoPostFix": "",
          "thousands": ".",
          "lengthMenu": "Registros a mostrar _MENU_",
          "loadingRecords": "Cargando...",
          "processing": "Procesando...",
          "search": "Buscar:",
          "zeroRecords": "No se obtuvo ninguna coincidencia",
          oPaginate: {
            sNext: '<i class="fas fa-arrow-circle-right"></i>',
            sPrevious: '<i class="fas fa-arrow-alt-circle-left"></i>',
            sFirst: '<i class="fa fa-step-backward"></i>',
            sLast: '<i class="fa fa-step-forward"></i>'
          }
        }
      });
    });
  </script>

  
  {%block extra%}
  

  {%endblock%}

vapunto/templates/caja.html
{%extends "index.html"%}

{%block formulario%}

{%load static%}

<!--End topbar header-->


<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Lista De Clientes
                <a href="{% url 'abrir_caja' 0 %}" data-toggle="tooltip" data-original-title="Apertura caja">
                    <i>Abrir Caja</i>
                </a>
                <a href="{% url 'retirar_caja' 0 %}" data-toggle="tooltip" data-original-title="Retirar caja">
                    <i>Retirar Caja </i>
                </a>
                <a href="#" data-toggle="tooltip" data-original-title="Cerrar Caja">
                    <i> Cerrar Caja</i>

                </a>
            </h5>
            <div class="table-responsive">
                <table class="table" id="datos">
                    <thead>
                        <tr>
                            <th >Usuario</a>
                            </th>
                            <th >Fecha</a>
                            </th>
                            <th >Hora</a></th>
    
                            <th >Motivo</a>
                            </th>
                            <th >tipo de mov.</a>
                            </th>
                            <th >Entrada</a>
                            </th>
                            <th >Salida</a>
                            </th>
                        </tr>
                    </thead>
                    {%for lista in parameter.listacaja %}
                        <tr>
                            
                            {%for usuario in parameters.listausuario %}
                            {%if usuario.codigo_usuario == lista.nombre_usuario_id%}
                            <td>{{usuario.nombre_usuario}}</td>
                            {%endif%}
                            {%endfor%}
                            <td>{{lista.fecha_caja}}</td>
                            <td>{{lista.hora_caja}}</td>
                            {% if lista.motivo_caja == null %}
                            <td>--------</td>
                            {% else %}
                            <td>{{lista.motivo_caja}}</td>
                            {% endif %}
                            {%if lista.tipo_mov == 1 %}<td>Retirar</td>{% endif %} 
                            {%if lista.tipo_mov == 2 %}<td>Apertura</td>{% endif %}
                            {%if lista.tipo_mov == 3 %}<td>Venta</td>{% endif %}
                            {% if lista.entrada_caja == null %}
                            <td>--------</td>
                            {% else %}
                            <td>{{lista.entrada_caja}}</td>
                            {% endif %}
                            {% if lista.salida_caja == null %}
                            <td>-------</td>
                            {% else %}
                            <td>{{lista.salida_caja}}</td>
                            {% endif %}
                        </tr> 
    
                    {%endfor%} 
                               
                   
                </table>
            </div>
        </div>
    </div>
</div>


{%endblock%}

{%block extra%}

{%endblock%}

vapunto/templates/error_403.html
{%extends "index.html"%}

{%block formulario%}

{%load static%}


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
    <div id="error">

        <div class="container text-center pt-32">
            <h1 class='error-title'>403</h1>
            <p>No puedes realizar esta accion</p>
            <a href="{% url 'port' %}" class='btn btn-primary'>Ir a Inicio</a>
        </div>


    </div>
</body>
{%endblock%}

vapunto/templates/invoice_pdf.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<style>
    .img-invoice {
        width: 50px;
        text-align: center;
        margin: 0 auto;
    }

    .head {
        text-align: center;
        text-transform: uppercase;
    }

    #invoice thead tr th {
        text-align: left;
        border-bottom: 1px solid black;
        border-top: 1px solid black;
        padding-top: 4px;
    }

    #invoice thead tr {
        margin-bottom: 0;
        padding-bottom: 0;
    }

    #invoice tbody tr {
        padding: 0;
    }

    .text-center {
        text-align: center;
    }
</style>
<body>
<img src="{{ icon }}" class="img-invoice">
<p class="head">
    {{ emp.name|upper }}<br>
    {{ emp.ruc }}<br>
    {{ emp.address|upper }}
</p>
<p>
    <b>FACTURA:</b> {{ sale.id }}<br> {# id de la venta #}
    <b>FECHA DE VENTA:</b> {{ sale.date_joined }}<br>
    <b>CLIENTE:</b> {{ sale.cli.names|upper }}<br>
    <b>CI | RUC:</b> {{ sale.cli.dni }}<br>
</p>
<table id="invoice">
    <thead>
    <tr>
        <th style="width: 20%;">CATEGORIA</th>
        <th style="width: 30%;">PRODUCTO</th>
        <th style="width: 10%;">CANT</th>
        <th style="width: 10%;">P.UNITARIO</th>
        <th style="width: 10%;">M. DE PAGO</th>
        <th style="text-align: right; width: 20%;">TOTAL</th>
    </tr>
    </thead>
    <tbody>
    {% for d in sale.detsale_set.all %}
        <tr {% if forloop.first %}style="padding-top: 3px;" {% endif %}>
            <td>{{ d.prod.cate.name }}</td>
            <td>{{ d.prod.name }}</td>
            <td>{{ d.cant }}</td>
            <td>Gs.{{ d.price }}</td>
            <td>{{ d.sale.pay.name }}</td>
            <td style="text-align: right;">Gs.{{ d.subtotal }}</td>
        </tr>
    {% endfor %}
    <tr style="border-top: 1px solid black; padding-top: 4px;">
        <td colspan="5"><b>SUBTOTAL</b></td>
        <td style="text-align: right">Gs.{{ sale.subtotal }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="5"><b>IVA 11%</b></td>
        <td style="text-align: right">Gs.{{ sale.iva }}</td>
    </tr>
    <tr style="padding-top: 0px;">
        <td colspan="5"><b>TOTAL A PAGAR</b></td>
        <td style="text-align: right">Gs.{{ sale.total }}</td>
    </tr>
    </tbody>
</table>
<table style="margin-top: 250px;">
    <thead>
    <tr>
        <th>*GRACIAS POR SU COMPRA*</th>
    </tr>
    <tr>
        <th>NO SE ACEPTAN CAMBIOS NI DEVOLUCIONES</th>
    </tr>
    </thead>
</table>
</body>

vapunto/templates/login.html
{%extends "base.html"%}

{%block cuerpo%}

{%load static%}

<body class="bg-theme bg-theme1">

<!-- start loader -->
   <div id="pageloader-overlay" class="visible incoming"><div class="loader-wrapper-outer"><div class="loader-wrapper-inner" ><div class="loader"></div></div></div></div>
   <!-- end loader -->

<!-- Start wrapper-->
 <div id="wrapper">

 <div class="loader-wrapper"><div class="lds-ring"><div></div><div></div><div></div><div></div></div></div>
	<div class="card card-authentication1 mx-auto my-5">
		<div class="card-body">
		 <div class="card-content p-2">
		 	<div class="text-center">
		 		<img src="{%static 'assets/images/logo-login.png'%}" alt="logo icon" class='logo-icon'>
		 	</div>
		  <div class="card-title text-uppercase text-center py-3">Para iniciar sesion ingresa sus credenciales </div>
      <form role="form" action="./" method="POST">
        {%csrf_token%}
			  <div class="form-group">
			  <label for="exampleInputUsername" class="sr-only">Nombre De Usuario</label>
			   <div class="position-relative has-icon-right">
				  <input type="text" id="exampleInputUsername" class="form-control input-shadow" placeholder="Ingrese Nombre de Usuario" name="Usuario">
				  <div class="form-control-position">
					  <i class="icon-user"></i>
				  </div>
			   </div>
			  </div>
			  <div class="form-group">
			  <label for="exampleInputPassword" class="sr-only">Password</label>
			   <div class="position-relative has-icon-right">
				  <input type="password" id="exampleInputPassword" class="form-control input-shadow" placeholder="Ingrese la Contraseña" name="Password">
				  <div class="form-control-position">
					  <i class="icon-lock"></i>
				  </div>
			   </div>
			  </div>
			
			 <button type="submit" class="btn btn-light btn-block">Iniciar Sesión</button>
			 <br></br>
       {% if mensaje_error %}
           <div class="alert alert-warning alert-dismissible fade show" role="alert">
                 <span class="alert-text"><strong>ATENCION.</strong> {{mensaje_error}}</span>
                     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                     </button>
            </div> 
         {% endif %}
      </form>
		   </div>
		   </div>
	    </div>
    
   
</body>

{%endblock%}